---

dependencies:
  - manikos.common
  - { role: manikos.nginx, become: yes }
  - { role: manikos.fail2ban, become: yes }
  - { role: manikos.ufw, become: yes }
  - { role: manikos.postgres, become: yes }
  - manikos.bitbucket
  - manikos.django  # pyenv & pip_tools roles are dependencies of this role
  - manikos.uwsgi
