---

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
  become: yes

- name: restart uwsgi
  systemd:
    name: uwsgi
    state: restarted
    enabled: yes
  become: yes
